name: Hello-World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
          echo "hello swaroop welcome to gha"
          echo "this is the second line"
